# Generated by Django 4.1.7 on 2025-04-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='albums', to='images.image', verbose_name='包含图片'),
        ),
    ]
