# Generated by Django 4.1.7 on 2025-04-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
